### ISSUE TITLE
UNION ALL with many columns may cause explain so slow

### ISSUE THREAD

**Issue by wuboy0307** [greenplum-db/gporca#523]
Greenplum: 5.19.0
PQO version: 3.42.0

Here is a simple example which has 20 SELECT UNION ALL and each table has 500 columns
https://gist.github.com/wuboy0307/3e67f1ebb9f28128e519679d158f9591

When I explain this query. It costs 30 seconds or more to finish.
However, if I turn off optimizer. It costs less than 1 second.

If I explain only one select with 500 columns. It's fast.
https://gist.github.com/wuboy0307/ab6f5b47768ea5bf5b8cf5b26524cb42

Also, if I explain 20 select with less(20) columns, it's also fast.
https://gist.github.com/wuboy0307/7843e4a3c952b7d49b9ce69b1afbfdf6

That issue only happen when there are many UNION ALL and many columns.

The example is quite simple that only have NULL as columns.
In my production databases, the explain process take forever to finish...

**Comment by chrishajas** [comment]
Thanks for the report and clear repro! Looked into this and the bulk of the slowdown here is due to hash collisions in our column hashmap. I've opened a PR (https://github.com/greenplum-db/gporca/pull/524)  that reduces the optimization time from ~25s to ~9s. There's still other improvements to optimization time (and really improving our hashmap/set hashing functions and implementation), but this was low-hanging fruit.
